import type { SidebarOptions } from "vuepress-theme-hope";

export const sidebar: SidebarOptions = {
  "/roadmap/": [
    { text: "路线总览", link: "/roadmap/" },
    {
      text: "🧭 认知",
      collapsible: false,
      children: [{ text: "01 认识测试开发", link: "/roadmap/01-what-is-sdet.html" }],
    },
    {
      text: "🧱 筑基",
      collapsible: false,
      children: [
        { text: "02 计算机基础", link: "/roadmap/02-cs-fundamentals.html" },
        { text: "03 编程语言", link: "/roadmap/03-programming.html" },
        { text: "04 工程基础", link: "/roadmap/04-engineering-basics.html" },
      ],
    },
    {
      text: "🧪 测试核心",
      collapsible: false,
      children: [
        { text: "05 测试理论与用例设计", link: "/roadmap/05-testing-theory.html" },
        { text: "06 接口测试与接口自动化", link: "/roadmap/06-api-automation.html" },
        { text: "07 UI 与 App 自动化", link: "/roadmap/07-ui-app-automation.html" },
        { text: "08 性能与稳定性测试", link: "/roadmap/08-performance-testing.html" },
        { text: "09 CI/CD、质量平台与精准测试", link: "/roadmap/09-quality-engineering.html" },
      ],
    },
    {
      text: "🤖 AI 时代",
      collapsible: false,
      children: [
        { text: "10 AI 辅助测试", link: "/roadmap/10-ai-assisted-testing.html" },
        { text: "11 AI 应用测试与大模型评测", link: "/roadmap/11-llm-evaluation.html" },
      ],
    },
    {
      text: "🚀 实战与求职",
      collapsible: false,
      children: [
        { text: "12 项目实战指南", link: "/roadmap/12-project-practice.html" },
        { text: "13 面试准备", link: "/roadmap/13-interview-guide.html" },
      ],
    },
  ],

  // 以下板块内容上线后在此扩展目录结构
  "/knowledge/": [
    { text: "实战教程", link: "/knowledge/" },
    {
      text: "AI 测试实战系列",
      collapsible: false,
      children: [
        { text: "01 用例设计四件套", link: "/knowledge/01-testcase-design-toolkit.html" },
        { text: "02 接口文档智能解析", link: "/knowledge/02-api-schema-parser.html" },
        { text: "03 测试数据构造", link: "/knowledge/03-api-testdata-generator.html" },
        { text: "04 脚本批量生成", link: "/knowledge/04-api-testscript-generator.html" },
        { text: "05 脚本质量优化", link: "/knowledge/05-api-test-optimizer.html" },
        { text: "06 智能执行调度", link: "/knowledge/06-api-test-executor.html" },
        { text: "07 失败自动诊断修复", link: "/knowledge/07-api-failure-diagnoser.html" },
        { text: "08 测试数据清理", link: "/knowledge/08-api-testdata-cleaner.html" },
        { text: "09 测试报告生成", link: "/knowledge/09-api-report-generator.html" },
        { text: "10 全链路流水线编排", link: "/knowledge/10-api-pipeline-scheduler.html" },
        { text: "11 UI 页面解析", link: "/knowledge/11-ui-page-parser.html" },
        { text: "12 UI 脚本批量生成", link: "/knowledge/12-ui-testscript-generator.html" },
        { text: "13 UI 脚本健壮性增强", link: "/knowledge/13-ui-testscript-enhancer.html" },
        { text: "14 视觉断言与多浏览器", link: "/knowledge/14-ui-visual-assert.html" },
        { text: "15 UI 智能执行调度", link: "/knowledge/15-ui-test-executor.html" },
        { text: "16 UI 失败诊断修复", link: "/knowledge/16-ui-failure-diagnoser.html" },
        { text: "17 UI 测试报告生成", link: "/knowledge/17-ui-report-generator.html" },
        { text: "18 UI 全链路编排", link: "/knowledge/18-ui-pipeline-scheduler.html" },
        { text: "19 脚本生成流水线串联", link: "/knowledge/19-ui-script-pipeline.html" },
        { text: "20 执行到报告全流程收官", link: "/knowledge/20-ui-full-flow-integration.html" },
      ],
    },
  ],
  "/interview/": [
    { text: "题库首页", link: "/interview/" },
    {
      text: "🤖 大模型测试",
      collapsible: false,
      children: [
        { text: "01 大模型测试与传统测试的本质区别", link: "/interview/llm-testing/01-llm-vs-traditional-testing.html" },
        { text: "02 LLM 知识库问答测试方案设计", link: "/interview/llm-testing/02-llm-kb-qa-test-plan.html" },
        { text: "03 大模型评测维度划分", link: "/interview/llm-testing/03-evaluation-dimensions.html" },
        { text: "04 测模型与测应用的边界", link: "/interview/llm-testing/04-model-vs-application-testing.html" },
        { text: "05 上线门禁怎么定", link: "/interview/llm-testing/05-release-gate.html" },
        { text: "06 评测集怎么建", link: "/interview/llm-testing/06-evalset-construction.html" },
        { text: "07 评测集怎么维护", link: "/interview/llm-testing/07-evalset-maintenance.html" },
        { text: "08 评测数据污染怎么防", link: "/interview/llm-testing/08-data-contamination.html" },
        { text: "09 常用评测指标", link: "/interview/llm-testing/09-evaluation-metrics.html" },
        { text: "10 LLM-as-a-Judge 的坑", link: "/interview/llm-testing/10-llm-as-a-judge.html" },
        { text: "11 人工评估怎么设计", link: "/interview/llm-testing/11-human-evaluation.html" },
        { text: "12 RAG 系统评测", link: "/interview/llm-testing/12-rag-evaluation.html" },
        { text: "13 幻觉与幻觉率测试", link: "/interview/llm-testing/13-hallucination-testing.html" },
        { text: "14 安全测试测什么", link: "/interview/llm-testing/14-security-testing.html" },
        { text: "15 红队测试怎么组织", link: "/interview/llm-testing/15-red-teaming.html" },
        { text: "16 性能测试关注什么", link: "/interview/llm-testing/16-performance-testing.html" },
        { text: "17 流式稳定性怎么测", link: "/interview/llm-testing/17-streaming-stability.html" },
        { text: "18 Prompt 回归测试", link: "/interview/llm-testing/18-prompt-regression.html" },
        { text: "19 CI/CD 集成评测", link: "/interview/llm-testing/19-cicd-integration.html" },
        { text: "20 Agent 应用测试", link: "/interview/llm-testing/20-agent-testing.html" },
      ],
    },
    {
      text: "🧪 软件测试必备",
      collapsible: false,
      children: [
        { text: "01 新项目怎么开展测试", link: "/interview/testing-essentials/01-new-project-test-process.html" },
        { text: "02 版本迭代日常流程", link: "/interview/testing-essentials/02-daily-iteration-workflow.html" },
        { text: "03 用例设计六法", link: "/interview/testing-essentials/03-testcase-design-methods.html" },
        { text: "04 登录页用例设计", link: "/interview/testing-essentials/04-login-page-test-design.html" },
        { text: "05 没有需求文档怎么测", link: "/interview/testing-essentials/05-testing-without-requirements.html" },
        { text: "06 bug 报告与生命周期", link: "/interview/testing-essentials/06-bug-report-lifecycle.html" },
        { text: "07 前端还是后端的 bug", link: "/interview/testing-essentials/07-frontend-vs-backend-bug.html" },
        { text: "08 偶现 bug 怎么处理", link: "/interview/testing-essentials/08-non-reproducible-bugs.html" },
        { text: "09 开发说不是 bug 怎么办", link: "/interview/testing-essentials/09-dispute-with-developers.html" },
        { text: "10 上线前一天的严重 bug", link: "/interview/testing-essentials/10-critical-bug-before-release.html" },
        { text: "11 App 与 Web 测试区别", link: "/interview/testing-essentials/11-app-vs-web-testing.html" },
        { text: "12 接口测试与无文档", link: "/interview/testing-essentials/12-api-testing-basics.html" },
        { text: "13 join 区别与手写 SQL", link: "/interview/testing-essentials/13-sql-join-basics.html" },
        { text: "14 性能测试与指标", link: "/interview/testing-essentials/14-performance-testing-basics.html" },
        { text: "15 什么项目适合自动化", link: "/interview/testing-essentials/15-automation-adoption-criteria.html" },
        { text: "16 框架分层与 PO 模式", link: "/interview/testing-essentials/16-framework-layering-po.html" },
        { text: "17 用例不稳定误报治理", link: "/interview/testing-essentials/17-flaky-test-governance.html" },
        { text: "18 版本测完可以上线吗", link: "/interview/testing-essentials/18-release-exit-criteria.html" },
        { text: "19 测试左移右移落地", link: "/interview/testing-essentials/19-shift-left-shift-right.html" },
        { text: "20 质量保证与测试价值", link: "/interview/testing-essentials/20-quality-assurance-value.html" },
      ],
    },
  ],
  "/resources/": [{ text: "资源导航", link: "/resources/" }],
  "/about/": [
    { text: "关于本路线", link: "/about/" },
    { text: "参与共建", link: "/about/contributing.html" },
    { text: "更新日志", link: "/about/changelog.html" },
  ],
};
