import type { SidebarOptions } from "vuepress-theme-hope";

export const sidebar: SidebarOptions = {
  "/roadmap/": [
    { text: "路线总览", link: "/roadmap/" },
    {
      text: "🧭 认知",
      collapsible: false,
      children: [{ text: "01 认识测试开发", link: "/roadmap/01-what-is-sdet.html" }],
    },
    {
      text: "🧱 筑基",
      collapsible: false,
      children: [
        { text: "02 计算机基础", link: "/roadmap/02-cs-fundamentals.html" },
        { text: "03 编程语言", link: "/roadmap/03-programming.html" },
        { text: "04 工程基础", link: "/roadmap/04-engineering-basics.html" },
      ],
    },
    {
      text: "🧪 测试核心",
      collapsible: false,
      children: [
        { text: "05 测试理论与用例设计", link: "/roadmap/05-testing-theory.html" },
        { text: "06 接口测试与接口自动化", link: "/roadmap/06-api-automation.html" },
        { text: "07 UI 与 App 自动化", link: "/roadmap/07-ui-app-automation.html" },
        { text: "08 性能与稳定性测试", link: "/roadmap/08-performance-testing.html" },
        { text: "09 CI/CD、质量平台与精准测试", link: "/roadmap/09-quality-engineering.html" },
      ],
    },
    {
      text: "🤖 AI 时代",
      collapsible: false,
      children: [
        { text: "10 AI 辅助测试", link: "/roadmap/10-ai-assisted-testing.html" },
        { text: "11 AI 应用测试与大模型评测", link: "/roadmap/11-llm-evaluation.html" },
      ],
    },
    {
      text: "🚀 实战与求职",
      collapsible: false,
      children: [
        { text: "12 项目实战指南", link: "/roadmap/12-project-practice.html" },
        { text: "13 面试准备", link: "/roadmap/13-interview-guide.html" },
      ],
    },
  ],

  // 以下板块内容上线后在此扩展目录结构
  "/knowledge/": [
    { text: "实战教程", link: "/knowledge/" },
    {
      text: "AI 测试实战系列",
      collapsible: true,
      children: [
        { text: "01 用例设计四件套", link: "/knowledge/01-testcase-design-toolkit.html" },
        { text: "02 接口文档智能解析", link: "/knowledge/02-api-schema-parser.html" },
        { text: "03 测试数据构造", link: "/knowledge/03-api-testdata-generator.html" },
        { text: "04 脚本批量生成", link: "/knowledge/04-api-testscript-generator.html" },
        { text: "05 脚本质量优化", link: "/knowledge/05-api-test-optimizer.html" },
        { text: "06 智能执行调度", link: "/knowledge/06-api-test-executor.html" },
        { text: "07 失败自动诊断修复", link: "/knowledge/07-api-failure-diagnoser.html" },
        { text: "08 测试数据清理", link: "/knowledge/08-api-testdata-cleaner.html" },
        { text: "09 测试报告生成", link: "/knowledge/09-api-report-generator.html" },
        { text: "10 全链路流水线编排", link: "/knowledge/10-api-pipeline-scheduler.html" },
        { text: "11 UI 页面解析", link: "/knowledge/11-ui-page-parser.html" },
        { text: "12 UI 脚本批量生成", link: "/knowledge/12-ui-testscript-generator.html" },
        { text: "13 UI 脚本健壮性增强", link: "/knowledge/13-ui-testscript-enhancer.html" },
        { text: "14 视觉断言与多浏览器", link: "/knowledge/14-ui-visual-assert.html" },
        { text: "15 UI 智能执行调度", link: "/knowledge/15-ui-test-executor.html" },
        { text: "16 UI 失败诊断修复", link: "/knowledge/16-ui-failure-diagnoser.html" },
        { text: "17 UI 测试报告生成", link: "/knowledge/17-ui-report-generator.html" },
        { text: "18 UI 全链路编排", link: "/knowledge/18-ui-pipeline-scheduler.html" },
        { text: "19 脚本生成流水线串联", link: "/knowledge/19-ui-script-pipeline.html" },
        { text: "20 执行到报告全流程收官", link: "/knowledge/20-ui-full-flow-integration.html" },
      ],
    },
  ],
  "/interview/": [
    { text: "题库首页", link: "/interview/" },
    {
      text: "🤖 大模型测试",
      collapsible: true,
      children: [
        { text: "01 大模型测试与传统测试的本质区别", link: "/interview/llm-testing/01-llm-vs-traditional-testing.html" },
        { text: "02 LLM 知识库问答测试方案设计", link: "/interview/llm-testing/02-llm-kb-qa-test-plan.html" },
        { text: "03 大模型评测维度划分", link: "/interview/llm-testing/03-evaluation-dimensions.html" },
        { text: "04 测模型与测应用的边界", link: "/interview/llm-testing/04-model-vs-application-testing.html" },
        { text: "05 上线门禁怎么定", link: "/interview/llm-testing/05-release-gate.html" },
        { text: "06 评测集怎么建", link: "/interview/llm-testing/06-evalset-construction.html" },
        { text: "07 评测集怎么维护", link: "/interview/llm-testing/07-evalset-maintenance.html" },
        { text: "08 评测数据污染怎么防", link: "/interview/llm-testing/08-data-contamination.html" },
        { text: "09 常用评测指标", link: "/interview/llm-testing/09-evaluation-metrics.html" },
        { text: "10 LLM-as-a-Judge 的坑", link: "/interview/llm-testing/10-llm-as-a-judge.html" },
        { text: "11 人工评估怎么设计", link: "/interview/llm-testing/11-human-evaluation.html" },
        { text: "12 RAG 系统评测", link: "/interview/llm-testing/12-rag-evaluation.html" },
        { text: "13 幻觉与幻觉率测试", link: "/interview/llm-testing/13-hallucination-testing.html" },
        { text: "14 安全测试测什么", link: "/interview/llm-testing/14-security-testing.html" },
        { text: "15 红队测试怎么组织", link: "/interview/llm-testing/15-red-teaming.html" },
        { text: "16 性能测试关注什么", link: "/interview/llm-testing/16-performance-testing.html" },
        { text: "17 流式稳定性怎么测", link: "/interview/llm-testing/17-streaming-stability.html" },
        { text: "18 Prompt 回归测试", link: "/interview/llm-testing/18-prompt-regression.html" },
        { text: "19 CI/CD 集成评测", link: "/interview/llm-testing/19-cicd-integration.html" },
        { text: "20 Agent 应用测试", link: "/interview/llm-testing/20-agent-testing.html" },
      ],
    },
    {
      text: "🧪 软件测试必备",
      collapsible: true,
      children: [
        { text: "01 新项目怎么开展测试", link: "/interview/testing-essentials/01-new-project-test-process.html" },
        { text: "02 版本迭代日常流程", link: "/interview/testing-essentials/02-daily-iteration-workflow.html" },
        { text: "03 用例设计六法", link: "/interview/testing-essentials/03-testcase-design-methods.html" },
        { text: "04 登录页用例设计", link: "/interview/testing-essentials/04-login-page-test-design.html" },
        { text: "05 没有需求文档怎么测", link: "/interview/testing-essentials/05-testing-without-requirements.html" },
        { text: "06 bug 报告与生命周期", link: "/interview/testing-essentials/06-bug-report-lifecycle.html" },
        { text: "07 前端还是后端的 bug", link: "/interview/testing-essentials/07-frontend-vs-backend-bug.html" },
        { text: "08 偶现 bug 怎么处理", link: "/interview/testing-essentials/08-non-reproducible-bugs.html" },
        { text: "09 开发说不是 bug 怎么办", link: "/interview/testing-essentials/09-dispute-with-developers.html" },
        { text: "10 上线前一天的严重 bug", link: "/interview/testing-essentials/10-critical-bug-before-release.html" },
        { text: "11 App 与 Web 测试区别", link: "/interview/testing-essentials/11-app-vs-web-testing.html" },
        { text: "12 接口测试与无文档", link: "/interview/testing-essentials/12-api-testing-basics.html" },
        { text: "13 join 区别与手写 SQL", link: "/interview/testing-essentials/13-sql-join-basics.html" },
        { text: "14 性能测试与指标", link: "/interview/testing-essentials/14-performance-testing-basics.html" },
        { text: "15 什么项目适合自动化", link: "/interview/testing-essentials/15-automation-adoption-criteria.html" },
        { text: "16 框架分层与 PO 模式", link: "/interview/testing-essentials/16-framework-layering-po.html" },
        { text: "17 用例不稳定误报治理", link: "/interview/testing-essentials/17-flaky-test-governance.html" },
        { text: "18 版本测完可以上线吗", link: "/interview/testing-essentials/18-release-exit-criteria.html" },
        { text: "19 测试左移右移落地", link: "/interview/testing-essentials/19-shift-left-shift-right.html" },
        { text: "20 质量保证与测试价值", link: "/interview/testing-essentials/20-quality-assurance-value.html" },
      ],
    },
    {
      text: "⚙️ 自动化测试",
      collapsible: true,
      children: [
        { text: "01 自动化的价值与 ROI", link: "/interview/automation-testing/01-automation-value-roi.html" },
        { text: "02 分层策略与比例", link: "/interview/automation-testing/02-test-pyramid-strategy.html" },
        { text: "03 UI 自动化覆盖与目标", link: "/interview/automation-testing/03-ui-automation-scope.html" },
        { text: "04 手工用例与自动化用例", link: "/interview/automation-testing/04-manual-vs-automated-cases.html" },
        { text: "05 Selenium 工作原理", link: "/interview/automation-testing/05-selenium-webdriver-principles.html" },
        { text: "06 元素定位方式与选择", link: "/interview/automation-testing/06-locator-strategies.html" },
        { text: "07 动态元素怎么定位", link: "/interview/automation-testing/07-dynamic-element-location.html" },
        { text: "08 三种等待方式", link: "/interview/automation-testing/08-wait-strategies.html" },
        { text: "09 定位不到元素排查", link: "/interview/automation-testing/09-element-not-found-troubleshooting.html" },
        { text: "10 iframe 多窗口弹窗", link: "/interview/automation-testing/10-iframe-window-alert.html" },
        { text: "11 验证码与上传下载", link: "/interview/automation-testing/11-captcha-upload-download.html" },
        { text: "12 PO 模式核心思想", link: "/interview/automation-testing/12-page-object-principles.html" },
        { text: "13 框架架构与从 0 搭建", link: "/interview/automation-testing/13-framework-architecture.html" },
        { text: "14 pytest fixture 与参数化", link: "/interview/automation-testing/14-pytest-fixture-conftest.html" },
        { text: "15 三种驱动模式区别", link: "/interview/automation-testing/15-data-keyword-bdd-driven.html" },
        { text: "16 用例执行体系设计", link: "/interview/automation-testing/16-execution-design.html" },
        { text: "17 CI/CD 接入与告警", link: "/interview/automation-testing/17-cicd-integration-alerts.html" },
        { text: "18 接口自动化框架设计", link: "/interview/automation-testing/18-api-automation-framework.html" },
        { text: "19 Appium 工作原理", link: "/interview/automation-testing/19-appium-principles.html" },
        { text: "20 Playwright 与 Selenium 选型", link: "/interview/automation-testing/20-playwright-vs-selenium.html" },
      ],
    },
    {
      text: "⚡ 性能测试",
      collapsible: true,
      children: [
        { text: "01 性能测试的目的与适用", link: "/interview/performance-testing/01-performance-testing-purpose.html" },
        { text: "02 四种测试类型区别", link: "/interview/performance-testing/02-load-stress-soak-spike.html" },
        { text: "03 TPS QPS RT 并发关系", link: "/interview/performance-testing/03-metrics-relationships.html" },
        { text: "04 为什么看 P95 P99", link: "/interview/performance-testing/04-percentile-response-time.html" },
        { text: "05 介入时机与完整流程", link: "/interview/performance-testing/05-performance-testing-process.html" },
        { text: "06 性能方案怎么设计", link: "/interview/performance-testing/06-test-plan-design.html" },
        { text: "07 并发用户数怎么估算", link: "/interview/performance-testing/07-concurrency-estimation.html" },
        { text: "08 压测环境怎么选", link: "/interview/performance-testing/08-environment-selection.html" },
        { text: "09 参数化与数据构造", link: "/interview/performance-testing/09-parameterization-testdata.html" },
        { text: "10 JMeter 与分布式压测", link: "/interview/performance-testing/10-jmeter-distributed-testing.html" },
        { text: "11 全链路压测", link: "/interview/performance-testing/11-full-link-load-testing.html" },
        { text: "12 瓶颈定位整体思路", link: "/interview/performance-testing/12-bottleneck-analysis.html" },
        { text: "13 常见瓶颈与分层判断", link: "/interview/performance-testing/13-common-bottlenecks.html" },
        { text: "14 慢 SQL 定位优化", link: "/interview/performance-testing/14-slow-sql-optimization.html" },
        { text: "15 浸泡测试与内存泄漏", link: "/interview/performance-testing/15-soak-testing-memory-leaks.html" },
        { text: "16 前端性能指标", link: "/interview/performance-testing/16-frontend-performance.html" },
        { text: "17 秒杀大促场景设计", link: "/interview/performance-testing/17-flash-sale-scenario.html" },
        { text: "18 报告与容量结论", link: "/interview/performance-testing/18-report-capacity-conclusion.html" },
        { text: "19 调优手段与测试角色", link: "/interview/performance-testing/19-tuning-tester-role.html" },
        { text: "20 环境质疑怎么处理", link: "/interview/performance-testing/20-environment-dispute.html" },
      ],
    },
    {
      text: "🔐 安全测试",
      collapsible: true,
      children: [
        { text: "01 安全与功能测试区别", link: "/interview/security-testing/01-security-vs-functional.html" },
        { text: "02 常见 Web 安全漏洞", link: "/interview/security-testing/02-common-web-vulnerabilities.html" },
        { text: "03 安全测试流程与黑白灰", link: "/interview/security-testing/03-security-testing-process.html" },
        { text: "04 安全融入日常工作", link: "/interview/security-testing/04-security-in-daily-work.html" },
        { text: "05 SQL 注入", link: "/interview/security-testing/05-sql-injection.html" },
        { text: "06 XSS 三种类型", link: "/interview/security-testing/06-xss-types.html" },
        { text: "07 CSRF 与 XSS 区别", link: "/interview/security-testing/07-csrf-vs-xss.html" },
        { text: "08 越权漏洞测试", link: "/interview/security-testing/08-broken-access-control.html" },
        { text: "09 文件上传漏洞", link: "/interview/security-testing/09-file-upload-vulnerabilities.html" },
        { text: "10 敏感信息泄露排查", link: "/interview/security-testing/10-sensitive-data-exposure.html" },
        { text: "11 登录安全测试", link: "/interview/security-testing/11-authentication-security.html" },
        { text: "12 接口签名与防重放", link: "/interview/security-testing/12-api-security-signature.html" },
        { text: "13 会话管理安全", link: "/interview/security-testing/13-session-management.html" },
        { text: "14 HTTPS 原理与抓包", link: "/interview/security-testing/14-https-and-capture.html" },
        { text: "15 安全测试工具箱", link: "/interview/security-testing/15-security-testing-tools.html" },
        { text: "16 漏洞定级与报告", link: "/interview/security-testing/16-vulnerability-reporting.html" },
        { text: "17 App 安全专项", link: "/interview/security-testing/17-mobile-security-testing.html" },
        { text: "18 SAST DAST SCA 与 CI", link: "/interview/security-testing/18-devsecops-sast-dast-sca.html" },
        { text: "19 等保与数据合规", link: "/interview/security-testing/19-compliance-mlps.html" },
        { text: "20 安全测试方案设计", link: "/interview/security-testing/20-security-test-plan.html" },
      ],
    },
    {
      text: "✨ AI 测试提效",
      collapsible: true,
      children: [
        { text: "01 AI 提效环节与实战", link: "/interview/ai-efficiency/01-ai-efficiency-scenarios.html" },
        { text: "02 提效效果怎么度量", link: "/interview/ai-efficiency/02-measuring-efficiency.html" },
        { text: "03 哪些环节适合 AI", link: "/interview/ai-efficiency/03-suitable-scenarios.html" },
        { text: "04 工具调研与选型", link: "/interview/ai-efficiency/04-tool-selection.html" },
        { text: "05 AI 生成用例与质量", link: "/interview/ai-efficiency/05-ai-testcase-generation.html" },
        { text: "06 用例 prompt 设计", link: "/interview/ai-efficiency/06-prompt-engineering.html" },
        { text: "07 新旧用例融合", link: "/interview/ai-efficiency/07-new-vs-legacy-cases.html" },
        { text: "08 AI 生成脚本与验证", link: "/interview/ai-efficiency/08-ai-script-generation.html" },
        { text: "09 CI 失败分析归类", link: "/interview/ai-efficiency/09-ci-failure-analysis.html" },
        { text: "10 AI 造数提效", link: "/interview/ai-efficiency/10-ai-testdata-generation.html" },
        { text: "11 精准测试与影响面", link: "/interview/ai-efficiency/11-precision-testing.html" },
        { text: "12 报告与文档提效", link: "/interview/ai-efficiency/12-ai-documentation.html" },
        { text: "13 幻觉风险控制", link: "/interview/ai-efficiency/13-hallucination-control.html" },
        { text: "14 代码数据合规", link: "/interview/ai-efficiency/14-compliance-risks.html" },
        { text: "15 团队推广破局", link: "/interview/ai-efficiency/15-team-adoption.html" },
        { text: "16 AI 资产沉淀管理", link: "/interview/ai-efficiency/16-ai-asset-management.html" },
        { text: "17 RAG 测试知识库", link: "/interview/ai-efficiency/17-rag-knowledge-base.html" },
        { text: "18 Agent 与自动化闭环", link: "/interview/ai-efficiency/18-agent-exploration.html" },
        { text: "19 编码助手的价值", link: "/interview/ai-efficiency/19-coding-assistants.html" },
        { text: "20 AI 时代核心竞争力", link: "/interview/ai-efficiency/20-core-competitiveness.html" },
      ],
    },
    {
      text: "📊 研发效能度量",
      collapsible: true,
      children: [
        { text: "01 什么是研发效能", link: "/interview/dev-efficiency/01-what-is-dev-efficiency.html" },
        { text: "02 度量体系怎么搭", link: "/interview/dev-efficiency/02-metrics-framework.html" },
        { text: "03 DORA 四大指标", link: "/interview/dev-efficiency/03-dora-metrics.html" },
        { text: "04 SPACE 框架", link: "/interview/dev-efficiency/04-space-framework.html" },
        { text: "05 测试效能指标", link: "/interview/dev-efficiency/05-testing-efficiency-metrics.html" },
        { text: "06 缺陷逃逸率", link: "/interview/dev-efficiency/06-defect-escape-rate.html" },
        { text: "07 自动化覆盖率", link: "/interview/dev-efficiency/07-automation-coverage.html" },
        { text: "08 MTTR MTTI 指标", link: "/interview/dev-efficiency/08-mttr-mtti.html" },
        { text: "09 速度质量冲突", link: "/interview/dev-efficiency/09-speed-quality-conflict.html" },
        { text: "10 效能数据采集", link: "/interview/dev-efficiency/10-data-collection.html" },
        { text: "11 度量陷阱与防坑", link: "/interview/dev-efficiency/11-metrics-pitfalls.html" },
        { text: "12 基线与目标值", link: "/interview/dev-efficiency/12-baseline-targets.html" },
        { text: "13 效能平台建设", link: "/interview/dev-efficiency/13-metrics-platform.html" },
        { text: "14 推动改进落地", link: "/interview/dev-efficiency/14-driving-improvements.html" },
        { text: "15 CICD 效能提升", link: "/interview/dev-efficiency/15-cicd-efficiency-gains.html" },
        { text: "16 交付周期瓶颈分析", link: "/interview/dev-efficiency/16-bottleneck-analysis.html" },
        { text: "17 效能提升案例", link: "/interview/dev-efficiency/17-efficiency-case-study.html" },
        { text: "18 防止度量变考核", link: "/interview/dev-efficiency/18-avoid-kpi-weaponization.html" },
        { text: "19 质量内建", link: "/interview/dev-efficiency/19-build-quality-in.html" },
        { text: "20 效能团队协作", link: "/interview/dev-efficiency/20-efficiency-team-collaboration.html" },
      ],
    },
    {
      text: "🛠️ 测试平台开发",
      collapsible: true,
      children: [
        { text: "01 为什么自研测试平台", link: "/interview/test-platform/01-why-build-inhouse.html" },
        { text: "02 从 0 到 1 规划", link: "/interview/test-platform/02-zero-to-one-roadmap.html" },
        { text: "03 技术选型与架构", link: "/interview/test-platform/03-tech-stack-architecture.html" },
        { text: "04 平台没人用怎么办", link: "/interview/test-platform/04-adoption-strategy.html" },
        { text: "05 用例管理模块设计", link: "/interview/test-platform/05-testcase-management.html" },
        { text: "06 接口平台核心设计", link: "/interview/test-platform/06-api-platform-design.html" },
        { text: "07 执行引擎设计", link: "/interview/test-platform/07-execution-engine.html" },
        { text: "08 定时任务与触发", link: "/interview/test-platform/08-scheduling-triggers.html" },
        { text: "09 报告体系设计", link: "/interview/test-platform/09-report-system.html" },
        { text: "10 多团队权限隔离", link: "/interview/test-platform/10-multi-tenant-permissions.html" },
        { text: "11 测试数据管理", link: "/interview/test-platform/11-testdata-management.html" },
        { text: "12 设备资源池化", link: "/interview/test-platform/12-device-farm-grid.html" },
        { text: "13 精准测试落地", link: "/interview/test-platform/13-precision-testing-platform.html" },
        { text: "14 平台稳定性保障", link: "/interview/test-platform/14-platform-stability.html" },
        { text: "15 价值度量与汇报", link: "/interview/test-platform/15-value-measurement-reporting.html" },
        { text: "16 低代码测试平台", link: "/interview/test-platform/16-lowcode-platform.html" },
        { text: "17 AI 升级机会点", link: "/interview/test-platform/17-ai-upgrade-opportunities.html" },
        { text: "18 技术栈与协作", link: "/interview/test-platform/18-techstack-teamwork.html" },
        { text: "19 需求优先级排序", link: "/interview/test-platform/19-requirement-prioritization.html" },
        { text: "20 平台成就与踩坑", link: "/interview/test-platform/20-platform-story.html" },
      ],
    },
    {
      text: "👥 测试管理",
      collapsible: true,
      children: [
        { text: "01 测试经理的职责", link: "/interview/test-management/01-test-manager-role.html" },
        { text: "02 新接手团队前三个月", link: "/interview/test-management/02-first-ninety-days.html" },
        { text: "03 质量目标与年度规划", link: "/interview/test-management/03-quality-goals-planning.html" },
        { text: "04 能力培养与分工", link: "/interview/test-management/04-team-development.html" },
        { text: "05 怎么招聘测试工程师", link: "/interview/test-management/05-hiring-testers.html" },
        { text: "06 多项目人力调配", link: "/interview/test-management/06-resource-allocation.html" },
        { text: "07 测试时间被压缩", link: "/interview/test-management/07-time-compression.html" },
        { text: "08 进度滞后怎么办", link: "/interview/test-management/08-progress-tracking.html" },
        { text: "09 发布质量关", link: "/interview/test-management/09-release-quality-gate.html" },
        { text: "10 线上事故处理", link: "/interview/test-management/10-incident-management.html" },
        { text: "11 漏测复盘改进", link: "/interview/test-management/11-missed-bug-retro.html" },
        { text: "12 测试开发冲突协调", link: "/interview/test-management/12-dev-test-conflicts.html" },
        { text: "13 推动上游改进", link: "/interview/test-management/13-upstream-improvement.html" },
        { text: "14 质量文化建设", link: "/interview/test-management/14-quality-culture.html" },
        { text: "15 外包管理配比", link: "/interview/test-management/15-outsourcing-management.html" },
        { text: "16 KPI 与 OKR 设计", link: "/interview/test-management/16-kpi-okr-design.html" },
        { text: "17 证明团队价值", link: "/interview/test-management/17-proving-team-value.html" },
        { text: "18 事故责任划分", link: "/interview/test-management/18-incident-responsibility.html" },
        { text: "19 团队转型自动化 AI", link: "/interview/test-management/19-team-transformation.html" },
        { text: "20 测试经理成长路径", link: "/interview/test-management/20-manager-career-path.html" },
      ],
    },
    {
      text: "🔄 测试流程与团队协作",
      collapsible: true,
      children: [
        { text: "01 需求评审怎么评审才到位", link: "/interview/test-process-collaboration/01-requirement-review.html" },
        { text: "02 敏捷与瀑布的测试差异", link: "/interview/test-process-collaboration/02-agile-vs-waterfall.html" },
        { text: "03 提测流程与提测标准", link: "/interview/test-process-collaboration/03-build-handover-standards.html" },
        { text: "04 冒烟测试谁来做", link: "/interview/test-process-collaboration/04-smoke-testing-ownership.html" },
        { text: "05 回归测试范围怎么定", link: "/interview/test-process-collaboration/05-regression-scope.html" },
        { text: "06 发布流程测试参与什么", link: "/interview/test-process-collaboration/06-release-process-involvement.html" },
        { text: "07 测试环境问题怎么应对", link: "/interview/test-process-collaboration/07-test-environment-issues.html" },
        { text: "08 需求变更频繁怎么应对", link: "/interview/test-process-collaboration/08-frequent-requirement-changes.html" },
        { text: "09 提测质量差修复慢怎么办", link: "/interview/test-process-collaboration/09-poor-quality-slow-fixes.html" },
        { text: "10 跨团队依赖协作测试", link: "/interview/test-process-collaboration/10-cross-team-dependencies.html" },
        { text: "11 测试左移个人实践", link: "/interview/test-process-collaboration/11-shift-left-personal-practice.html" },
        { text: "12 线上用户反馈怎么响应", link: "/interview/test-process-collaboration/12-production-user-feedback.html" },
        { text: "13 测试工作量估算与排期", link: "/interview/test-process-collaboration/13-effort-estimation-planning.html" },
        { text: "14 站会与迭代回顾怎么参与", link: "/interview/test-process-collaboration/14-standup-retrospective.html" },
        { text: "15 团队流程问题与改进", link: "/interview/test-process-collaboration/15-process-improvement.html" },
        { text: "16 计划方案报告怎么写", link: "/interview/test-process-collaboration/16-test-plan-report-docs.html" },
        { text: "17 小团队没流程怎么开展", link: "/interview/test-process-collaboration/17-small-team-no-process.html" },
        { text: "18 DevOps 下测试角色变化", link: "/interview/test-process-collaboration/18-devops-role-change.html" },
        { text: "19 推行新流程遇抵触怎么办", link: "/interview/test-process-collaboration/19-rollout-resistance.html" },
        { text: "20 讲一个印象最深的版本", link: "/interview/test-process-collaboration/20-memorable-release-story.html" },
      ],
    },
  ],
  "/resources/": [
    { text: "资源导航", link: "/resources/" },
    {
      text: "🧰 测试工具清单",
      collapsible: true,
      children: [
        { text: "工具清单总览", link: "/resources/test-tools/" },
        {
          text: "AI 编程工具",
          collapsible: true,
          children: [
            { text: "清单总览", link: "/resources/test-tools/ai-coding-tools/" },
            { text: "01 Claude Code", link: "/resources/test-tools/ai-coding-tools/01-claude-code.html" },
            { text: "02 Codex", link: "/resources/test-tools/ai-coding-tools/02-codex.html" },
            { text: "03 Gemini CLI", link: "/resources/test-tools/ai-coding-tools/03-gemini-cli.html" },
            { text: "04 GitHub Copilot", link: "/resources/test-tools/ai-coding-tools/04-github-copilot.html" },
            { text: "05 Antigravity", link: "/resources/test-tools/ai-coding-tools/05-antigravity.html" },
            { text: "06 Grok Build", link: "/resources/test-tools/ai-coding-tools/06-grok-build.html" },
            { text: "07 Cursor", link: "/resources/test-tools/ai-coding-tools/07-cursor.html" },
            { text: "08 Amp", link: "/resources/test-tools/ai-coding-tools/08-amp.html" },
            { text: "09 Droid", link: "/resources/test-tools/ai-coding-tools/09-droid.html" },
            { text: "10 Kiro", link: "/resources/test-tools/ai-coding-tools/10-kiro.html" },
            { text: "11 Zed", link: "/resources/test-tools/ai-coding-tools/11-zed.html" },
            { text: "12 Warp", link: "/resources/test-tools/ai-coding-tools/12-warp.html" },
            { text: "13 Qoder", link: "/resources/test-tools/ai-coding-tools/13-qoder.html" },
            { text: "14 Qwen Code", link: "/resources/test-tools/ai-coding-tools/14-qwen-code.html" },
            { text: "15 CodeBuddy", link: "/resources/test-tools/ai-coding-tools/15-codebuddy.html" },
            { text: "16 WorkBuddy", link: "/resources/test-tools/ai-coding-tools/16-workbuddy.html" },
            { text: "17 Kimi For Coding", link: "/resources/test-tools/ai-coding-tools/17-kimi-for-coding.html" },
            { text: "18 ZCode", link: "/resources/test-tools/ai-coding-tools/18-zcode.html" },
            { text: "19 DeepSeek Harness", link: "/resources/test-tools/ai-coding-tools/19-deepseek-harness.html" },
            { text: "20 Mimo", link: "/resources/test-tools/ai-coding-tools/20-mimo.html" },
            { text: "21 TraeWork", link: "/resources/test-tools/ai-coding-tools/21-traework.html" },
            { text: "22 豆包工作", link: "/resources/test-tools/ai-coding-tools/22-doubao-work.html" },
            { text: "23 Cline", link: "/resources/test-tools/ai-coding-tools/23-cline.html" },
            { text: "24 Roo Code", link: "/resources/test-tools/ai-coding-tools/24-roo-code.html" },
            { text: "25 Kilo Code", link: "/resources/test-tools/ai-coding-tools/25-kilo-code.html" },
            { text: "26 Kilo CLI", link: "/resources/test-tools/ai-coding-tools/26-kilo-cli.html" },
            { text: "27 OpenCode", link: "/resources/test-tools/ai-coding-tools/27-opencode.html" },
            { text: "28 pi", link: "/resources/test-tools/ai-coding-tools/28-pi.html" },
            { text: "29 OMP（Oh My Pi）", link: "/resources/test-tools/ai-coding-tools/29-omp.html" },
            { text: "30 Every Code", link: "/resources/test-tools/ai-coding-tools/30-every-code.html" },
            { text: "31 Goose", link: "/resources/test-tools/ai-coding-tools/31-goose.html" },
            { text: "32 OpenClaw", link: "/resources/test-tools/ai-coding-tools/32-openclaw.html" },
            { text: "33 Hermes", link: "/resources/test-tools/ai-coding-tools/33-hermes.html" },
          ],
        },
        {
          text: "接口测试工具",
          collapsible: true,
          children: [
            { text: "清单总览", link: "/resources/test-tools/api-testing-tools/" },
            { text: "01 Postman", link: "/resources/test-tools/api-testing-tools/01-postman.html" },
            { text: "02 Apifox", link: "/resources/test-tools/api-testing-tools/02-apifox.html" },
            { text: "03 Insomnia", link: "/resources/test-tools/api-testing-tools/03-insomnia.html" },
            { text: "04 APIpost", link: "/resources/test-tools/api-testing-tools/04-apipost.html" },
            { text: "05 Eolink", link: "/resources/test-tools/api-testing-tools/05-eolink.html" },
            { text: "06 Bruno", link: "/resources/test-tools/api-testing-tools/06-bruno.html" },
            { text: "07 Hoppscotch", link: "/resources/test-tools/api-testing-tools/07-hoppscotch.html" },
            { text: "08 WireMock", link: "/resources/test-tools/api-testing-tools/08-wiremock.html" },
            { text: "09 HTTPie", link: "/resources/test-tools/api-testing-tools/09-httpie.html" },
            { text: "10 Hurl", link: "/resources/test-tools/api-testing-tools/10-hurl.html" },
            { text: "11 Apache JMeter", link: "/resources/test-tools/api-testing-tools/11-jmeter.html" },
            { text: "12 Karate", link: "/resources/test-tools/api-testing-tools/12-karate.html" },
            { text: "13 REST Assured", link: "/resources/test-tools/api-testing-tools/13-rest-assured.html" },
            { text: "14 HttpRunner", link: "/resources/test-tools/api-testing-tools/14-httprunner.html" },
            { text: "15 Playwright API", link: "/resources/test-tools/api-testing-tools/15-playwright-api.html" },
            { text: "16 Newman", link: "/resources/test-tools/api-testing-tools/16-newman.html" },
            { text: "17 MeterSphere", link: "/resources/test-tools/api-testing-tools/17-metersphere.html" },
            { text: "18 Tavern", link: "/resources/test-tools/api-testing-tools/18-tavern.html" },
            { text: "19 soapUI", link: "/resources/test-tools/api-testing-tools/19-soapui.html" },
            { text: "20 Yaak", link: "/resources/test-tools/api-testing-tools/20-yaak.html" },
            { text: "21 Robot Framework + Requests", link: "/resources/test-tools/api-testing-tools/21-robot-framework-requests.html" },
            { text: "22 Reqable", link: "/resources/test-tools/api-testing-tools/22-reqable.html" },
            { text: "23 Swagger Inspector", link: "/resources/test-tools/api-testing-tools/23-swagger-inspector.html" },
          ],
        },
        {
          text: "UI 自动化工具",
          collapsible: true,
          children: [
            { text: "清单总览", link: "/resources/test-tools/ui-automation-tools/" },
            { text: "01 Selenium", link: "/resources/test-tools/ui-automation-tools/01-selenium.html" },
            { text: "02 Playwright", link: "/resources/test-tools/ui-automation-tools/02-playwright.html" },
            { text: "03 Cypress", link: "/resources/test-tools/ui-automation-tools/03-cypress.html" },
            { text: "04 Puppeteer", link: "/resources/test-tools/ui-automation-tools/04-puppeteer.html" },
            { text: "05 TestCafe", link: "/resources/test-tools/ui-automation-tools/05-testcafe.html" },
            { text: "06 Nightwatch.js", link: "/resources/test-tools/ui-automation-tools/06-nightwatch.html" },
            { text: "07 CodeceptJS", link: "/resources/test-tools/ui-automation-tools/07-codeceptjs.html" },
            { text: "08 Mabl", link: "/resources/test-tools/ui-automation-tools/08-mabl.html" },
            { text: "09 Testim", link: "/resources/test-tools/ui-automation-tools/09-testim.html" },
            { text: "10 QA Wolf", link: "/resources/test-tools/ui-automation-tools/10-qa-wolf.html" },
            { text: "11 Playwright MCP", link: "/resources/test-tools/ui-automation-tools/11-playwright-mcp.html" },
            { text: "12 Playwright CLI", link: "/resources/test-tools/ui-automation-tools/12-playwright-cli.html" },
            { text: "13 BrowserSkill（腾讯）", link: "/resources/test-tools/ui-automation-tools/13-browserskill.html" },
            { text: "14 BrowserAct", link: "/resources/test-tools/ui-automation-tools/14-browseract.html" },
            { text: "15 Browser MCP", link: "/resources/test-tools/ui-automation-tools/15-browser-mcp.html" },
            { text: "16 Stagehand", link: "/resources/test-tools/ui-automation-tools/16-stagehand.html" },
            { text: "17 Browser Use", link: "/resources/test-tools/ui-automation-tools/17-browser-use.html" },
            { text: "18 Skyvern", link: "/resources/test-tools/ui-automation-tools/18-skyvern.html" },
            { text: "19 Nova Act（亚马逊）", link: "/resources/test-tools/ui-automation-tools/19-nova-act.html" },
            { text: "20 Notte", link: "/resources/test-tools/ui-automation-tools/20-notte.html" },
            { text: "21 Browserbase", link: "/resources/test-tools/ui-automation-tools/21-browserbase.html" },
            { text: "22 Steel", link: "/resources/test-tools/ui-automation-tools/22-steel.html" },
            { text: "23 Hyperbrowser", link: "/resources/test-tools/ui-automation-tools/23-hyperbrowser.html" },
            { text: "24 Appium", link: "/resources/test-tools/ui-automation-tools/24-appium.html" },
            { text: "25 Airtest", link: "/resources/test-tools/ui-automation-tools/25-airtest.html" },
            { text: "26 Maestro", link: "/resources/test-tools/ui-automation-tools/26-maestro.html" },
            { text: "27 Espresso", link: "/resources/test-tools/ui-automation-tools/27-espresso.html" },
            { text: "28 XCUITest", link: "/resources/test-tools/ui-automation-tools/28-xctest.html" },
            { text: "29 Detox", link: "/resources/test-tools/ui-automation-tools/29-detox.html" },
            { text: "30 WinAppDriver", link: "/resources/test-tools/ui-automation-tools/30-winappdriver.html" },
            { text: "31 FlaUI", link: "/resources/test-tools/ui-automation-tools/31-flaui.html" },
            { text: "32 PyAutoGUI", link: "/resources/test-tools/ui-automation-tools/32-pyautogui.html" },
            { text: "33 pywinauto", link: "/resources/test-tools/ui-automation-tools/33-pywinauto.html" },
            { text: "34 WebdriverIO", link: "/resources/test-tools/ui-automation-tools/34-webdriverio.html" },
            { text: "35 Robot Framework", link: "/resources/test-tools/ui-automation-tools/35-robot-framework.html" },
            { text: "36 Katalon Studio", link: "/resources/test-tools/ui-automation-tools/36-katalon.html" },
            { text: "37 TestComplete", link: "/resources/test-tools/ui-automation-tools/37-testcomplete.html" },
            { text: "38 Midscene（字节）", link: "/resources/test-tools/ui-automation-tools/38-midscene.html" },
            { text: "39 testRigor", link: "/resources/test-tools/ui-automation-tools/39-testrigor.html" },
          ],
        },
        { text: "⚡ 性能测试工具（规划中）", link: "/resources/test-tools/performance-testing-tools/" },
        { text: "🔐 安全测试工具（规划中）", link: "/resources/test-tools/security-testing-tools/" },
      ],
    },
    { text: "📚 推荐书单（规划中）", link: "/resources/books/" },
    { text: "🎓 课程与教程（规划中）", link: "/resources/courses/" },
    { text: "💬 社区与信息源（规划中）", link: "/resources/communities/" },
    { text: "🎯 练手平台与靶场（规划中）", link: "/resources/practice-platforms/" },
  ],
  "/about/": [
    { text: "关于本路线", link: "/about/" },
    { text: "参与共建", link: "/about/contributing.html" },
    { text: "更新日志", link: "/about/changelog.html" },
  ],
};
